baseURL: "/"
languageCode: "ru-ru"
defaultContentLanguage: "ru"
title: ITdoxy
paginate: 5
theme: PaperMod

permalinks:
  posts: /:slug/

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  ru:
    languageName: "Русский"
    menu:
      main:
        - name: Категории
          url: /categories/
          weight: 1
        - name: Теги
          url: /tags/
          weight: 2
        - name: Архив
          url: /archives/
          weight: 3
        - name: Поиск
          url: /search/
          weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  dateFormat: "02.01.2006"

  ShowReadingTime: true
  ShowShareButtons: true
  defaultTheme: auto
  disableThemeToggle: false

  # opengraph
  title: ITdoxy
  description: Поваренная книга программиста
  images:
    - background-1920x1080.jpg

  # home-info mode
  homeInfoParams:
    Title: "Поваренная книга программиста"
    Content: "У нас вы сможете найти разнообразные статьи в сфере информационных технологий, посвящённые системному и сетевому администрированию, программированию, базам данных, Linux и не только."

  socialIcons:
    - name: telegram
      url: "https://t.me/ITdoxy"
    - name: twitter
      url: "https://twitter.com/ITdoxy"
    - name: vk
      url: "https://vk.com/itdoxy"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
